name: 'CI\CD'

on:
    push:
        branches:
            - "main"
            - "develop"
            - "release/**"
            - "feature/**"

jobs:
    build:
        runs-on: ubuntu-latest

        outputs:
            tag: ${{ steps.version-generator.outputs.tag }}

        steps:
            - name: Checkout source
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0

            - name: Setup .NET 7
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "7.0.x"

            - name: Auth nuget source
              run: dotnet nuget add source --username stefc --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/stefc/index.json"

            - name: Restore dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --no-restore -c Release

            - name: Test
              run: dotnet test --no-build -c Release --verbosity normal

            - name: Release or PreRelease
              id: package-version
              run: |
                  if [$REF == 'refs/heads/main']
                  then
                    echo "package_version=${{ env.GitBuildVersionSimple }}" >> $GITHUB_ENV
                  else
                    echo "package_version=${{ env.GitAssemblyInformationalVersion }}" >> $GITHUB_ENV
                  fi
              env:
                  REF: ${{ github.ref }}

            - name: Upload artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: stefc.mosmix.v${{ env.package_version }}.nupkg
                  path: src/bin/Release/*.nupkg

            - name: Set job outputs
              id: version-generator
              run: echo "tag=v${{ env.package_version }}" >> $GITHUB_OUTPUT

    deploy-dev:
        runs-on: ubuntu-latest
        needs: build
        if: ${{ github.ref == 'refs/heads/develop' }}
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v3
              with:
                  name: stefc.mosmix.${{ needs.build.outputs.tag }}.nupkg
                  path: artifacts

            - name: Publish the package to nuget.org
              run: dotnet nuget push artifacts/*.nupkg --api-key ${{ secrets.NUGET_AUTH_TOKEN }} --source https://api.nuget.org/v3/index.json

    deploy-release:
        runs-on: ubuntu-latest
        needs: build
        if: ${{ github.ref == 'refs/heads/main' }}
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v3
              with:
                  name: stefc.mosmix.${{ needs.build.outputs.tag }}.nupkg
                  path: artifacts

            - name: Publish the package to nuget.org
              run: dotnet nuget push artifacts/*.nupkg --api-key ${{ secrets.NUGET_AUTH_TOKEN }} --source https://api.nuget.org/v3/index.json

            - name: Generate changelog
              id: changelog
              uses: jaywcjlove/changelog-generator@v1.6.3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Create release
              uses: ncipollo/release-action@v1
              with:
                  artifacts: "artifacts/*.nupkg"
                  body: |
                      ${{ steps.changelog.outputs.changelog }}
                  token: ${{ secrets.GITHUB_TOKEN }}
                  tag: "${{ needs.build.outputs.tag }}"

            - name: Auth nuget source
              run: dotnet nuget add source --username stefc --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/stefc/index.json"

            - name: Publish the package to github
              run: dotnet nuget push artifacts/*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }} --source "github"

